# GLOBALS (TODO: read from config.json)
TILE_SIZE = 32
WORLD_WIDTH = 30
WORLD_HEIGHT = 17
MENU_HEIGHT = 2
SCREEN_WIDTH = WORLD_WIDTH * TILE_SIZE
SCREEN_HEIGHT = (WORLD_HEIGHT + MENU_HEIGHT) * TILE_SIZE
# TODO: Should these be global?
GAME_AREA = (SCREEN_WIDTH, WORLD_HEIGHT*TILE_SIZE)
MENU_AREA = (SCREEN_WIDTH, MENU_HEIGHT*TILE_SIZE)
MAX_BEES = 200